Pre!
Within bar!
Exception causing an exception: haha
   callcc_tcatch2.sl:28 <inline> &causeException()
   callcc_tcatch2.sl:9 <origin of exception>
After exception
42
